# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine: true

    working_directory: /go/src/github.com/snow-flake/sphlib-3.0
    steps:
      - checkout
      - run: apt-get update && apt-get install -y build-essential

      # specify any bash command here prefixed with `run: `
      - run: ./c/build.sh

